[toolchain]
profile = "minimal"
# Support diagnostic attributes used by the filesystem packer's dependencies.
channel = "nightly-2024-05-02"
components = ["rust-src", "llvm-tools-preview", "rustfmt", "clippy"]
